colors:
  primary:
    background: "#1E1E2E" # base
    foreground: "#CDD6F4" # text
    # Bright and dim foreground colors
    dim_foreground: "#CDD6F4" # text
    bright_foreground: "#CDD6F4" # text

  # Cursor colors
  cursor:
    text: "#1E1E2E" # base
    cursor: "#F5E0DC" # rosewater
  vi_mode_cursor:
    text: "#1E1E2E" # base
    cursor: "#B4BEFE" # lavender

  # Search colors
  search:
    matches:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
    focused_match:
      foreground: "#1E1E2E" # base
      background: "#A6E3A1" # green
    footer_bar:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Keyboard regex hints
  hints:
    start:
      foreground: "#1E1E2E" # base
      background: "#F9E2AF" # yellow
    end:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Selection colors
  selection:
    text: "#1E1E2E" # base
    background: "#F5E0DC" # rosewater

  # Normal colors
  normal:
    black: "#3A3C50" # Increase lightness
    red: "#F75C7A" # Increase saturation and lightness
    green: "#94F289" # Increase saturation and lightness
    yellow: "#FFD13F" # Increase saturation and lightness
    blue: "#7F9FFA" # Increase saturation and lightness
    magenta: "#F57ACB" # Increase saturation and lightness
    cyan: "#8AF7E9" # Increase saturation and lightness
    white: "#B4BCEA" # Increase lightness

  # Bright colors
  bright:
    black: "#474A5F" # Increase lightness
    red: "#FF708B" # Increase saturation and lightness
    green: "#A0FFAA" # Increase saturation and lightness
    yellow: "#FFE76A" # Increase saturation and lightness
    blue: "#96BDFE" # Increase saturation and lightness
    magenta: "#FF8ED3" # Increase saturation and lightness
    cyan: "#9EFFF7" # Increase saturation and lightness
    white: "#BAC2DE" # No change

  # Dim colors
  dim:
    black: "#36384D" # Increase lightness
    red: "#F75C7A" # Increase saturation and lightness
    green: "#94F289" # Increase saturation and lightness
    yellow: "#FFD13F" # Increase saturation and lightness
    blue: "#7F9FFA" # Increase saturation and lightness
    magenta: "#F57ACB" # Increase saturation and lightness
    cyan: "#8AF7E9" # Increase saturation and lightness
    white: "#A7AFC5" # Increase lightness

  indexed_colors:
    - { index: 16, color: "#FAB387" }
    - { index: 17, color: "#F5E0DC" }
