colors:
  primary:
    background: "#1E1E2E" # base
    foreground: "#CDD6F4" # text
    # Bright and dim foreground colors
    dim_foreground: "#CDD6F4" # text
    bright_foreground: "#CDD6F4" # text

  # Cursor colors
  cursor:
    text: "#1E1E2E" # base
    cursor: "#F5E0DC" # rosewater
  vi_mode_cursor:
    text: "#1E1E2E" # base
    cursor: "#B4BEFE" # lavender

  # Search colors
  search:
    matches:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
    focused_match:
      foreground: "#1E1E2E" # base
      background: "#A6E3A1" # green
    footer_bar:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Keyboard regex hints
  hints:
    start:
      foreground: "#1E1E2E" # base
      background: "#F9E2AF" # yellow
    end:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Selection colors
  selection:
    text: "#1E1E2E" # base
    background: "#F5E0DC" # rosewater

  # Default colors
  primary:
    background: '0x24292e'
    foreground: '0xd1d5da'

  # Normal colors
  normal:
    black: '0x24292e'
    red: '0xf14c4c'
    green: '0x23d18b'
    yellow: '0xe2e210'
    blue: '0x3b8eea'
    magenta: '0xbc3fbc'
    cyan: '0x29b7da'
    white: '0xd1d5da'

  # Bright colors
  bright:
    black: '0x666666'
    red: '0xf14c4c'
    green: '0x23d18b'
    yellow: '0xf5f543'
    blue: '0x3b8eea'
    magenta: '0xd670d6'
    cyan: '0x29b7da'
    white: '0xd1d5da'

  custom:
  #   - { index: 16, color: '0xd18616' }
  #   - { index: 17, color: '0xf14c4c' }

  indexed_colors:
    - { index: 16, color: "#FAB387" }
    - { index: 17, color: "#F5E0DC" }
