# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
#
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
window:
  # Window dimensions (changes require restart)
  #
  # Number of lines/columns (not pixels) in the terminal. The number of columns
  # must be at least `2`, while using a value of `0` for columns and lines will
  # fall back to the window manager's recommended size.
  #dimensions:
  #  columns: 0
  #  lines: 0
  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 5
    y: 0

  # Spread additional padding evenly around the terminal content.
  #dynamic_padding: false
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background and no title bar buttons
  #decorations: full
  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.7
  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed
  # Window title
  # title: Alacritty
  # Allow terminal applications to change Alacritty's window title.
  #dynamic_title: true
  # Window class (Linux/BSD only):
  #class:
  # Application instance name
  #instance: Alacritty
  # General application class
  #general: Alacritty
  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark`
  # and `light`. Set this to `None` to use the default theme variant.
  #gtk_theme_variant: None
  #scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  #history: 10000
  # Scrolling distance multiplier.
  #multiplier: 3

# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
    # Point size
    #size: 11.0
    # Offset is the extra space around each character. `offset.y` can be thought
    # of as modifying the line spacing, and `offset.x` as modifying the letter
    # spacing.
    #offset:
    #  x: 0
    #  y: 0
    # Glyph offset determines the locations of the glyphs within their cells with
    # the default being at the bottom. Increasing `x` moves the glyph to the
    # right, increasing `y` moves the glyph upward.
    #glyph_offset:
    #  x: 0
    #  y: 0
    # Thin stroke font rendering (macOS only)
    #
    # Thin strokes are suitable for retina displays, but for non-retina screens
    # it is recommended to set `use_thin_strokes` to `false`.
    #use_thin_strokes: true
    # Use built-in font for box drawing characters.
    #
    # If `true`, Alacritty will use a custom built-in font for box drawing
    # characters (Unicode points 2500 - 259f).
    #
    #builtin_box_drawing: true
    # If `true`, bold text is drawn using the bright color variants.
    #draw_bold_text_with_bright_colors: false
    # Colors (Tomorrow Night)
    #  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []
  # Transparent cell backgrounds
  #
  # Whether or not `window.opacity` applies to all cell backgrounds or only to
  # the default background. When set to `true` all cells will be transparent
  # regardless of their background color.
  #transparent_background_colors: false
  # Bell
  #
  # The bell is rung every time the BEL control character is received.
  #bell:
  # Visual Bell Animation
  #
  # Animation effect for flashing the screen when the visual bell is rung.
  #
  # Values for `animation`:
  #   - Ease
  #   - EaseOut
  #   - EaseOutSine
  #   - EaseOutQuad
  #   - EaseOutCubic
  #   - EaseOutQuart
  #   - EaseOutQuint
  #   - EaseOutExpo
  #   - EaseOutCirc
  #   - Linear
  #animation: EaseOutExpo
  # Duration of the visual bell flash in milliseconds. A `duration` of `0` will
  # disable the visual bell animation.
  #duration: 0
  # Visual bell animation color.
  #color: '#ffffff'
  # Bell Command
  #
  # This program is executed whenever the bell is rung.
  #
  # When set to `command: None`, no command will be executed.
  #
  # Example:
  #   command:
  #     program: notify-send
  #     args: ["Hello, World!"]
  #
  #command: None
  #selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false
scrolling:
  multiplier: 1
  faux_multiplier: 1
cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Beam
    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On
  # Vi mode cursor style
  #
  # If the vi mode cursor style is `None` or not specified, it will fall back to
  # the style of the active value of the normal cursor.
  #
  # See `cursor.style` for available options.
  #vi_mode_style: None
  # Cursor blinking interval in milliseconds.
  #blink_interval: 750
  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  #unfocused_hollow: false
  # Thickness of the cursor relative to the cell width as floating point number
  # from `0.0` to `1.0`.
  #thickness: 0.15
  # Live config reload (changes require restart)
  #live_config_reload: true
  # Shell
  #
  # You can set `shell.program` to the path of your favorite shell, e.g.
  # `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
  # shell.
  #
  # Default:
  #   - (macOS) /bin/bash --login
  #   - (Linux/BSD) user login shell
  #   - (Windows) powershell
  #shell:
  #  program: /bin/bash
  #  args:
  #    - --login
  # Startup directory
  #
  # Directory the shell is started in. If this is unset, or `None`, the working
  # directory of the parent process will be used.
  #working_directory: None
  # Send ESC (\x1b) before characters when alt is pressed.
  #alt_send_esc: true
  # Offer IPC using `alacritty msg` (unix only)
  #ipc_socket: true
  #mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }
  # If this is `true`, the cursor is temporarily hidden when typing.
  #hide_when_typing: false
  # Regex hints
  #
  # Terminal hints can be used to find text in the visible part of the terminal
  # and pipe it to other applications.
  #hints:
  # Keys used for the hint labels.
  #alphabet: "jfkdls;ahgurieowpq"
  # List with all available hints
  #
  # Each hint must have a `regex` and either an `action` or a `command` field.
  # The fields `mouse`, `binding` and `post_processing` are optional.
  #
  # The fields `command`, `binding.key`, `binding.mods`, `binding.mode` and
  # `mouse.mods` accept the same values as they do in the `key_bindings` sect
# Features not needed because of tmux
# key_bindings:
#   # scrollback
#   - { key: PageUp,   mods: Shift,         mode: ~Alt,        action: ReceiveChar }
#   - { key: PageDown, mods: Shift,         mode: ~Alt,        action: ReceiveChar }
#   - { key: Home,     mods: Shift,         mode: ~Alt,        action: ReceiveChar }
#   - { key: End,      mods: Shift,         mode: ~Alt,        action: ReceiveChar }
#   - { key: K,        mods: Command,       mode: ~Vi|~Search, action: ReceiveChar }
#   # searching
#   - { key: F,        mods: Control|Shift, mode: ~Search,     action: ReceiveChar }
#   - { key: F,        mods: Command,       mode: ~Search,     action: ReceiveChar }
#   - { key: B,        mods: Control|Shift, mode: ~Search,     action: ReceiveChar }
#   - { key: B,        mods: Command,       mode: ~Search,     action: ReceiveChar }
#   # copy/paste
#   # - { key: Paste,                                            action: ReceiveChar }
#   # - { key: Copy,                                             action: ReceiveChar }
#   # - { key: V,        mods: Control|Shift, mode: ~Vi,         action: ReceiveChar }
#   # - { key: V,        mods: Command,                          action: ReceiveChar }
#   # - { key: C,        mods: Control|Shift,                    action: ReceiveChar }
#   # - { key: C,        mods: Command,                          action: ReceiveChar }
#   # - { key: C,        mods: Control|Shift, mode: Vi|~Search,  action: ReceiveChar }
#   # - { key: C,        mods: Command,       mode: Vi|~Search,  action: ReceiveChar }
#   # - { key: Insert,   mods: Shift,                            action: ReceiveChar }
#
# mouse_bindings:
#   - { mouse: Right,  action: ReceiveChar }
#
# scrolling:
#   history: 0
#
# selection:
#   save_to_clipboard: false
colors:
  # Default colors
  primary:
    background: "0x0d1117"
    foreground: "0xb3b1ad"

  # Normal colors
  normal:
    black: "0x484f58"
    red: "0xff7b72"
    green: "0x3fb950"
    yellow: "0xd29922"
    blue: "0x58a6ff"
    magenta: "0xbc8cff"
    cyan: "0x39c5cf"
    white: "0xb3b1ad"

  # Bright colors
  bright:
    black: "0x6e7681"
    red: "0xffa198"
    green: "0x56d364"
    yellow: "0xe3b341"
    blue: "0x79c0ff"
    magenta: "0xd2a8ff"
    cyan: "0x39c5cf"
    white: "0xb3b1ad"

  indexed_colors:
    - { index: 16, color: "0xd18616" }
    - { index: 17, color: "0xffa198" }
theme: github_dark_default
