import = ["/home/pedro/.config/alacritty/themes/custom.toml"]

[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 19.0

[font.offset]
x = 0
y = 0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
multiplier = 1

[window]
opacity = 0.7
blur = true
decorations = "Buttonless"
option_as_alt = "Both"
dynamic_padding = true

[window.padding]
x = 0
y = 0
